server:
  port: 8080

app:
  security:
    trust-inbound-headers: false
    publicRoutes:
      - "/v1/auth/**"
      - "/webhook/**"

  rate-limit:
    method: fixed
    use-case:
      api-key:
        requests-per-minute: 200


spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              uri: lb://merchant-service
              predicates:
                - Path=/v1/auth/**, /v1/merchants/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                  - Path=/v1/orders/**, /v1/payments/**

            - id: vault-service
              uri: lb://vault-service
              predicates:
                - Path=/v1/vault/**

            - id: operations-service
              uri: lb://operations-service
              predicates:
                - Path=/webhook/**
                
jwt:
  secret-key: ${JWT_SECRET_KEY}

                
